routes/admin.php
<?php

use App\Http\Controllers\Admin\LanguagesController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AdminController;
use Illuminate\Support\Facades\Auth;



Route::get('/', [App\Http\Controllers\HomeController::class, 'welcome']);

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
    //home route
    Route::get('/', [AdminController::class, 'index'])->name('home');





Route::get('admin', 'App\Http\Controllers\Admin\AdminController@index');
Route::get('roles/bulk_delete',['App\Http\Controllers\Admin\RolesController','bulkDelete'])->name('roles.bulk_delete');
Route::resource('roles', 'App\Http\Controllers\Admin\RolesController');

Route::get('permissions/bulk_delete',['App\Http\Controllers\Admin\PermissionsController','bulkDelete'])->name('permissions.bulk_delete');
Route::resource('permissions', 'App\Http\Controllers\Admin\PermissionsController');

Route::get('users/bulk_delete',['App\Http\Controllers\Admin\UsersController','bulkDelete'])->name('users.bulk_delete');
Route::resource('users', 'App\Http\Controllers\Admin\UsersController')->middleware('auth');

Route::resource('pages', 'App\Http\Controllers\Admin\PagesController');
Route::resource('activitylogs', 'App\Http\Controllers\Admin\ActivityLogsController')->only([
    'index', 'show', 'destroy',
]);
Route::get('settings/bulk_delete',['App\Http\Controllers\Admin\SettingsController','bulkDelete'])->name('settings.bulk_delete');

Route::resource('settings', 'App\Http\Controllers\Admin\SettingsController');

Route::get('generator', ['uses' => '\acmepackage\LaravelAdmin\Controllers\ProcessController@getGenerator'])->name('generator');
Route::post('generator', ['uses' => '\acmepackage\LaravelAdmin\Controllers\ProcessController@postGenerator']);

Route::get('languages/bulk_delete',['App\Http\Controllers\Admin\LanguagesController','bulkDelete'])->name('languages.bulk_delete');
Route::resource('languages', LanguagesController::class);

});

Auth::routes();

Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard');
Route::get('/lang/{locale}', [App\Http\Controllers\HomeController::class, 'lang'])->name('lang');

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/lang/{locale}', [App\Http\Controllers\HomeController::class, 'lang'])->name('lang');


require('admin.php');

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\LogOptions;


class Role extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'label'];

    /**
     * A role may be given various permissions.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function permissions()
    {
        return $this->belongsToMany(Permission::class);
    }

    /**
     * Grant the given permission to a role.
     *
     * @param  Permission $permission
     *
     * @return mixed
     */
    public function givePermissionTo(Permission $permission)
    {
        return $this->permissions()->save($permission);
    }

    /**
     * Change activity log event description
     *
     * @param string $eventName
     *
     * @return string
     */
    public function getDescriptionForEvent($eventName)
    {
        return __CLASS__ . " model has been {$eventName}";
    }

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults();
    }
}

app/Http/Controllers/Admin/RolesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Role;
use App\Models\Permission;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;

class RolesController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
//        $this->middleware('can:read_roles')->only(['index']);
//        $this->middleware('can:create_roles')->only(['create', 'store']);
//        $this->middleware('can:update_roles')->only(['edit', 'update']);
//        $this->middleware('can:delete_roles')->only(['delete', 'bulk_delete']);
    }// end of __construct

    /**
     * Display a listing of the resource.
     *
     * @return void
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = Role::latest();
            return DataTables::of($data)
                ->addColumn('actions', function ($row){
                    $btn = '<a href="'. route('admin.roles.edit', $row->id) .'" class="btn btn-success btn-sm"><i class="fa fa-edit"></i> </a>';
                    $btn .= '<a href="'. route('admin.roles.show', $row->id) .'" class="btn btn-primary btn-sm ml-1 mr-1"><i class="fa  fa-eye"></i> </a>';
                    $btn .= '<form action="'. route('admin.roles.destroy', $row->id) .'" class="my-1 my-xl-0" method="post" style="display: inline-block;">';
                    $btn .= '<input name="_method" type="hidden" value="DELETE"><input name="_token" type="hidden" value="'.csrf_token().'">';
                    $btn .= '<button type="submit" class="btn btn-danger btn-sm  btn-jinja-delete"><i class="fa  fa-trash"></i> </button>';
                    $btn .= '</form>';
                    return $btn;
                })
                ->rawColumns(['actions'])
                ->make(true);
        }
        return view('admin.roles.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return void
     */
    public function create()
    {
        $role = new Role();
        $permissions = Permission::select('id', 'name', 'label')->get()->pluck('label', 'name');

        return view('admin.roles.create', compact(['permissions', 'role']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     *
     * @return void
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'label' => 'required'
        ]);
        $requestData = $request->all();

        $role = Role::create($requestData);
        $role->permissions()->detach();

        if ($request->has('permissions')) {
            foreach ($request->permissions as $permission_name) {
                $permission = Permission::whereName($permission_name)->first();
                $role->givePermissionTo($permission);
            }
        }

        return redirect('admin/roles')->with('flash_message',  __('general.added_successfully'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     *
     * @return void
     */
    public function show($id)
    {
        $role = Role::findOrFail($id);

        return view('admin.roles.show', compact('role'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     *
     * @return void
     */
    public function edit($id)
    {
        $role = Role::findOrFail($id);
        $permissions = Permission::select('id', 'name', 'label')->get()->pluck('label', 'name');

        return view('admin.roles.edit', compact('role', 'permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     *
     * @return void
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'label' => 'required'
        ]);

        $role = Role::findOrFail($id);
        $role->update($request->all());
        $role->permissions()->detach();

        if ($request->has('permissions')) {
            foreach ($request->permissions as $permission_name) {
                $permission = Permission::whereName($permission_name)->first();
                $role->givePermissionTo($permission);
            }
        }

        return redirect('admin/roles')->with('flash_message', __('general.updated_successfully'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     *
     * @return void
     */
    public function destroy($id)
    {
        $data = Role::FindOrFail($id);
        $data->permissions()->detach();
        $data->delete();

        return redirect('admin/roles')->with('flash_message', __('general.deleted_successfully'));
    }

    public function bulkDelete()
    {
        foreach (json_decode(request()->record_ids) as $recordId) {

            $data = Role::FindOrFail($recordId);
            $data->permissions()->detach();
            $data->delete();

        }//end of for each

        return redirect('admin/roles')->with('flash_message',  __('general.deleted_successfully'));
    }// end of bulkDelete
}

resources/views/admin/roles/create.blade.php
@extends('layouts.acme.admin.app')

@section('title')
    @lang('roles.roles')
@endsection


@section('content')
    <div class="app-content content">
        @include ('layouts.acme.admin._card_header', ['routeGroup' => 'admin', 'viewName' => 'roles', 'type' => 'create'])
        <div class="content-body">
            <!-- Form Section -->
            <section class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">@lang('general.create')</h4>
                            <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                    <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-content collpase show">
                            <div class="card-body">
                                <form method="POST" class="form form-horizontal" action="{{route('admin.roles.store')}}"  enctype="multipart/form-data">
                                    @csrf

                                    @include ('admin.roles.form', ['formMode' => 'create'])

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!--/ Form Sections -->
        </div>
    </div>
@endsection

@push('scripts')

@endpush

resources/views/admin/roles/edit.blade.php
@extends('layouts.acme.admin.app')

@section('title')
    @lang('roles.roles')
@endsection



@section('content')
    <div class="app-content content">
        @include ('layouts.acme.admin._card_header', ['routeGroup' => 'admin', 'viewName' => 'roles', 'type' => 'update'])
        <div class="content-body">
            <!-- Form Section -->
            <section class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">@lang('general.update')</h4>
                            <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                    <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-content collpase show">
                            <div class="card-body">
                                <form method="POST" class="form form-horizontal" action="{{route('admin.roles.update', $role->id)}}"  enctype="multipart/form-data">
                                    @method('PUT')
                                    @csrf

                                    @include ('admin.roles.form', ['formMode' => 'edit'])

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!--/ Form Sections -->
        </div>
    </div>
@endsection

@push('scripts')

@endpush

resources/views/admin/roles/form.blade.php
<div class="form-body">
    <div class="form-group{{ $errors->has('name') ? ' has-error' : ''}}">
        {!! Form::label('name', 'Name: ', ['class' => 'control-label']) !!}
        {!! Form::text('name', $role->name, ['class' => 'form-control', 'required' => 'required']) !!}
        {!! $errors->first('name', '<p class="text-danger help-block">:message</p>') !!}
    </div>
    <div class="form-group{{ $errors->has('label') ? ' has-error' : ''}}">
        {!! Form::label('label', 'Label: ', ['class' => 'control-label']) !!}
        {!! Form::text('label', $role->label, ['class' => 'form-control']) !!}
        {!! $errors->first('label', '<p class="text-danger help-block">:message</p>') !!}
    </div>
    <div class="form-group{{ $errors->has('label') ? ' has-error' : ''}}">
        {!! Form::label('label', 'Permissions: ', ['class' => 'control-label']) !!}
        {!! Form::select('permissions[]', $permissions, isset($role) ? $role->permissions->pluck('name') : [], ['class' => 'form-control select-custom', 'multiple' => true]) !!}
        {!! $errors->first('label', '<p class="text-danger help-block">:message</p>') !!}
    </div>
</div>
<div class="form-actions text-right">
    <button type="submit" class="btn btn-success">
        <i class="la la-check-square-o"></i> @lang('general.save')
    </button>
</div>

resources/views/admin/roles/index.blade.php
@extends('layouts.acme.admin.app')

@section('title')
@lang('roles.roles')
@endsection



@section('content')
<div class="app-content content">
    @include ('layouts.acme.admin._card_header', ['routeGroup' => 'admin', 'viewName' => 'roles', 'type' => 'index'])
    <div class="content-body">
        <!-- datatable -->
        <section class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">@lang('general.all') @lang('roles.roles')</h4>
                        <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                        <div class="heading-elements">
                            <ul class="list-inline mb-0">
                                <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="card-content collapse show">
                        <div class="card-body card-dashboard">
                            <div class="table  ">
                                <table class="table table-striped table-bordered zero-configuration data-table w-100">
                                    <thead>
                                        <tr>

                                            <th dt-type="text" dt-name="name">{{ trans('roles.name') }}</th>
                                            <th dt-type="text" dt-name="label">{{ trans('roles.label') }}</th>
                                            <th style="width: 25%;">@lang('general.action')</th>
                                        </tr>
                                        <tr id="searchable-row" @if(app()->getLocale() == 'ar') dir="rtl" @endif></tr>
                                    </thead>
                                    <tbody>

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--/ datatable -->
    </div>
</div>
@endsection

@push('scripts')
<script>
    var lang = '{{app()->getLocale()}}';
        var dataTablesSearchLink = '{{url('admin/roles')}}';
        const dataTablesLanguageLink = '{{(app()->getLocale() == 'ar')? asset('datatables/lang/ar.json') : asset('datatables/lang/en.json')}}';
</script>
<script src="{{asset('datatables/js/datatable.js')}}"></script>
@endpush

resources/views/admin/roles/show.blade.php
@extends('layouts.acme.admin.app')

@section('title')
    @lang('roles.roles')
@endsection



@section('content')
    <div class="app-content content">
        @include ('layouts.acme.admin._card_header', ['routeGroup' => 'admin', 'viewName' => 'roles', 'type' => 'show'])
        <div class="content-body">
            <!-- datatable -->
            <section class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">@lang('general.show')</h4>
                            <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                    <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-content collapse show">
                            <div class="card-body card-dashboard">
                                <div class="table-responsive">
                                    <table class="table">
                                        <tbody>
                                        <tr>
                                            <th>ID</th><td>{{ $role->id }}</td>
                                        </tr>
                                        <tr>
                                            <th> {{ trans('roles.name') }} </th><td> {{ $role->name }} </td></tr>
                                        <tr>
                                            <th> {{ trans('roles.label') }} </th><td> {{ $role->label }} </td>
                                        </tr>

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!--/ datatable -->
        </div>
    </div>
@endsection

@push('scripts')

@endpush