routes/admin.php
<?php

use App\Http\Controllers\Admin\LanguagesController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AdminController;
use Illuminate\Support\Facades\Auth;



Route::get('/', [App\Http\Controllers\HomeController::class, 'welcome']);

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
    //home route
    Route::get('/', [AdminController::class, 'index'])->name('home');





Route::get('admin', 'App\Http\Controllers\Admin\AdminController@index');
Route::get('roles/bulk_delete',['App\Http\Controllers\Admin\RolesController','bulkDelete'])->name('roles.bulk_delete');
Route::resource('roles', 'App\Http\Controllers\Admin\RolesController');

Route::get('permissions/bulk_delete',['App\Http\Controllers\Admin\PermissionsController','bulkDelete'])->name('permissions.bulk_delete');
Route::resource('permissions', 'App\Http\Controllers\Admin\PermissionsController');

Route::get('users/bulk_delete',['App\Http\Controllers\Admin\UsersController','bulkDelete'])->name('users.bulk_delete');
Route::resource('users', 'App\Http\Controllers\Admin\UsersController')->middleware('auth');

Route::resource('pages', 'App\Http\Controllers\Admin\PagesController');
Route::resource('activitylogs', 'App\Http\Controllers\Admin\ActivityLogsController')->only([
    'index', 'show', 'destroy',
]);
Route::get('settings/bulk_delete',['App\Http\Controllers\Admin\SettingsController','bulkDelete'])->name('settings.bulk_delete');

Route::resource('settings', 'App\Http\Controllers\Admin\SettingsController');

Route::get('generator', ['uses' => '\acmepackage\LaravelAdmin\Controllers\ProcessController@getGenerator'])->name('generator');
Route::post('generator', ['uses' => '\acmepackage\LaravelAdmin\Controllers\ProcessController@postGenerator']);

Route::get('languages/bulk_delete',['App\Http\Controllers\Admin\LanguagesController','bulkDelete'])->name('languages.bulk_delete');
Route::resource('languages', LanguagesController::class);

});

Auth::routes();

Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard');
Route::get('/lang/{locale}', [App\Http\Controllers\HomeController::class, 'lang'])->name('lang');

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/lang/{locale}', [App\Http\Controllers\HomeController::class, 'lang'])->name('lang');


require('admin.php');

app/Models/Language.php
<?php

namespace App\Models;

use App\Traits\HasTranslations;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\LogOptions;
use Illuminate\Database\Eloquent\SoftDeletes;

class Language extends Model
{
    use HasTranslations;
    use SoftDeletes;


    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'languages';

    /**
     * The database primary key value.
     *
     * @var string
     */
    protected $primaryKey = 'id';

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['code', 'name', 'icon'];
    public $translatable = [];



    /**
     * Change activity log event description
     *
     * @param string $eventName
     *
     * @return string
     */
    public function getDescriptionForEvent($eventName)
    {
        return __CLASS__ . " model has been {$eventName}";
    }

    public function getCreatedAtAttribute()
    {
        return Carbon::parse($this->attributes['created_at'])->format('Y-m-d\TH:i:s');
    }

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults();
    }
}

app/Http/Controllers/Admin/LanguagesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests;

use App\Models\Language;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;

class LanguagesController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
//        $this->middleware('can:read_users')->only(['index']);
//        $this->middleware('can:create_users')->only(['create', 'store']);
//        $this->middleware('can:update_users')->only(['edit', 'update']);
//        $this->middleware('can:delete_users')->only(['delete', 'bulk_delete']);
    }// end of __construct

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\View\View
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = Language::latest();
            return DataTables::of($data)
                ->addColumn('actions', function ($row){
                    $btn = '<a href="'. route('admin.languages.edit', $row->id) .'" class="btn btn-success btn-sm"><i class="fa fa-edit"></i> </a>';
                    $btn .= '<a href="'. route('admin.languages.show', $row->id) .'" class="btn btn-primary btn-sm ml-1 mr-1"><i class="fa  fa-eye"></i> </a>';
                    $btn .= '<form action="'. route('admin.languages.destroy', $row->id) .'" class="my-1 my-xl-0" method="post" style="display: inline-block;">';
                    $btn .= '<input name="_method" type="hidden" value="DELETE"><input name="_token" type="hidden" value="'.csrf_token().'">';
                    $btn .= '<button type="submit" class="btn btn-danger btn-sm  btn-jinja-delete"><i class="fa fa-trash"></i> </button>';
                    $btn .= '</form>';
                    return $btn;
                })
                ->rawColumns([ 'actions'])
                ->make(true);
        }

        return view('admin.languages.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        $language = new Language();
        return view('admin.languages.create', compact(['language']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        $this->validate($request, [
			'code' => 'required',
			'name' => 'required',
			'icon' => 'required'
		]);
        $requestData = $request->all();

        Language::create($requestData);

        return redirect('admin/languages')->with('flash_message',  __('general.added_successfully'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\View\View
     */
    public function show($id)
    {
        $language = Language::findOrFail($id);

        return view('admin.languages.show', compact('language'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\View\View
     */
    public function edit($id)
    {
        $language = Language::findOrFail($id);

        return view('admin.languages.edit', compact('language'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param  int  $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
			'code' => 'required',
			'name' => 'required',
            'icon' => 'required'
		]);
        $requestData = $request->all();

        $language = Language::findOrFail($id);
        $language->update($requestData);

        return redirect('admin/languages')->with('flash_message', __('general.updated_successfully'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy($id)
    {
        Language::destroy($id);

        return redirect('admin/languages')->with('flash_message', __('general.deleted_successfully'));
    }

    public function bulkDelete()
    {
        foreach (json_decode(request()->record_ids) as $recordId) {

            $data = Language::FindOrFail($recordId);
            $data->delete();

        }//end of for each

        return redirect('admin/languages')->with('flash_message',  __('general.deleted_successfully'));
    }// end of bulkDelete
}

resources/views/admin/languages/create.blade.php
@extends('layouts.acme.admin.app')

@section('title')
    @lang('languages.languages')
@endsection


@section('content')
    <div class="app-content content">
        @include ('layouts.acme.admin._card_header', ['routeGroup' => 'admin', 'viewName' => 'languages', 'type' => 'create'])
        <div class="content-body">
            <!-- Form Section -->
            <section class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">@lang('general.create')</h4>
                            <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                    <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-content collpase show">
                            <div class="card-body">
                                <form method="POST" class="form form-horizontal" action="{{route('admin.languages.store')}}"  enctype="multipart/form-data">
                                @csrf

                                @include ('admin.languages.form', ['formMode' => 'create'])

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!--/ Form Sections -->
        </div>
    </div>
@endsection

@push('scripts')

@endpush

resources/views/admin/languages/edit.blade.php
@extends('layouts.acme.admin.app')

@section('title')
    @lang('languages.languages')
@endsection

@section('content')
    <div class="app-content content">
        @include ('layouts.acme.admin._card_header', ['routeGroup' => 'admin', 'viewName' => 'languages', 'type' => 'update'])
        <div class="content-body">
            <!-- Form Section -->
            <section class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">@lang('general.update')</h4>
                            <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                    <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-content collpase show">
                            <div class="card-body">
                                <form method="POST" class="form form-horizontal" action="{{route('admin.languages.update', $language->id)}}"  enctype="multipart/form-data">
                                @method('PUT')
                                @csrf

                                    @include ('admin.languages.form', ['formMode' => 'edit'])

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!--/ Form Sections -->
        </div>
    </div>
@endsection

@push('scripts')

@endpush

resources/views/admin/languages/form.blade.php
<div class="form-body">
<div class="form-group{{ $errors->has('code') ? 'has-error' : ''}}">
    {!! Form::label('code', trans('languages.code'), ['class' => 'control-label']) !!}
    {!! Form::text('code', $language->code, ('required' == 'required') ? ['class' => 'form-control', 'required' => 'required'] : ['class' => 'form-control']) !!}

    {!! $errors->first('code', '<p class="text-danger help-block">:message</p>') !!}
</div>

<div class="form-group{{ $errors->has('name') ? 'has-error' : ''}}">
    {!! Form::label('name', trans('languages.name'), ['class' => 'control-label']) !!}
    {!! Form::text('name', $language->name, ('required' == 'required') ? ['class' => 'form-control', 'required' => 'required'] : ['class' => 'form-control']) !!}

    {!! $errors->first('name', '<p class="text-danger help-block">:message</p>') !!}
</div>

<div class="form-group{{ $errors->has('icon') ? 'has-error' : ''}}">
    {!! Form::label('icon', trans('languages.icon'), ['class' => 'control-label']) !!}
    {!! Form::text('icon', $language->icon, ('required' == 'required') ? ['class' => 'form-control', 'required' => 'required'] : ['class' => 'form-control']) !!}

    {!! $errors->first('icon', '<p class="text-danger help-block">:message</p>') !!}
</div>


</div>
<div class="form-actions text-right">
    <button type="submit" class="btn btn-jinja">
        <i class="la la-check-square-o"></i> @lang('general.save')
    </button>
</div>

resources/views/admin/languages/index.blade.php
@extends('layouts.acme.admin.app')

@section('title')
@lang('languages.languages')
@endsection


@section('content')
<div class="app-content content">
    @include ('layouts.acme.admin._card_header', ['routeGroup' => 'admin', 'viewName' => 'languages', 'type' =>
    'index'])
    <div class="content-body">
        <!-- datatable -->
        <section class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">@lang('general.all') @lang('languages.languages')</h4>
                        <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                        <div class="heading-elements">
                            <ul class="list-inline mb-0">
                                <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="card-content collapse show">
                        <div class="card-body card-dashboard">
                            <div class="table  ">
                                <table class="table table-striped table-bordered zero-configuration data-table w-100">
                                    <thead>
                                        <tr>
                                            <th dt-type="text" dt-name="code">{{ trans('languages.code') }}</th>
                                            <th dt-type="text" dt-name="name">{{ trans('languages.name') }}</th>
                                            <th style="width: 25%;">@lang('general.action')</th>
                                        </tr>
                                        <tr id="searchable-row"></tr>
                                    </thead>
                                    <tbody>

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--/ datatable -->
    </div>
</div>
@endsection

@push('scripts')
<script>
    var lang = '{{app()->getLocale()}}';
        var dataTablesSearchLink = '{{url('admin/languages')}}';
        var dataTablesLanguageLink = '{{(app()->getLocale() == 'ar')? asset('datatables/lang/ar.json') : asset('datatables/lang/en.json')}}';
</script>
<script src="{{asset('datatables/js/datatable.js')}}"></script>
@endpush

resources/views/admin/languages/show.blade.php
@extends('layouts.acme.admin.app')

@section('title')
    @lang('languages.languages')
@endsection


@section('content')
    <div class="app-content content">
        @include ('layouts.acme.admin._card_header', ['routeGroup' => 'admin', 'viewName' => 'languages', 'type' => 'show'])
        <div class="content-body">
            <!-- datatable -->
            <section class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">@lang('general.show')</h4>
                            <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                    <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-content collapse show">
                            <div class="card-body card-dashboard">
                                <div class="table-responsive">
                                    <table class="table">
                                        <tbody>
                                            <tr>
                                                <th>ID</th><td>{{ $language->id }}</td>
                                            </tr>
                                            <tr><th> {{ trans('languages.code') }} </th><td> {{ $language->code }} </td></tr><tr><th> {{ trans('languages.name') }} </th><td> {{ $language->name }} </td></tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!--/ datatable -->
        </div>
    </div>
@endsection

@push('scripts')

@endpush