routes/admin.php
<?php

use App\Http\Controllers\Admin\LanguagesController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AdminController;
use Illuminate\Support\Facades\Auth;



Route::get('/', [App\Http\Controllers\HomeController::class, 'welcome']);

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
    //home route
    Route::get('/', [AdminController::class, 'index'])->name('home');





Route::get('admin', 'App\Http\Controllers\Admin\AdminController@index');
Route::get('roles/bulk_delete',['App\Http\Controllers\Admin\RolesController','bulkDelete'])->name('roles.bulk_delete');
Route::resource('roles', 'App\Http\Controllers\Admin\RolesController');

Route::get('permissions/bulk_delete',['App\Http\Controllers\Admin\PermissionsController','bulkDelete'])->name('permissions.bulk_delete');
Route::resource('permissions', 'App\Http\Controllers\Admin\PermissionsController');

Route::get('users/bulk_delete',['App\Http\Controllers\Admin\UsersController','bulkDelete'])->name('users.bulk_delete');
Route::resource('users', 'App\Http\Controllers\Admin\UsersController')->middleware('auth');

Route::resource('pages', 'App\Http\Controllers\Admin\PagesController');
Route::resource('activitylogs', 'App\Http\Controllers\Admin\ActivityLogsController')->only([
    'index', 'show', 'destroy',
]);
Route::get('settings/bulk_delete',['App\Http\Controllers\Admin\SettingsController','bulkDelete'])->name('settings.bulk_delete');

Route::resource('settings', 'App\Http\Controllers\Admin\SettingsController');

Route::get('generator', ['uses' => '\acmepackage\LaravelAdmin\Controllers\ProcessController@getGenerator'])->name('generator');
Route::post('generator', ['uses' => '\acmepackage\LaravelAdmin\Controllers\ProcessController@postGenerator']);

Route::get('languages/bulk_delete',['App\Http\Controllers\Admin\LanguagesController','bulkDelete'])->name('languages.bulk_delete');
Route::resource('languages', LanguagesController::class);

});

Auth::routes();

Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard');
Route::get('/lang/{locale}', [App\Http\Controllers\HomeController::class, 'lang'])->name('lang');

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/lang/{locale}', [App\Http\Controllers\HomeController::class, 'lang'])->name('lang');


require('admin.php');

resources/views/admin/pages/create.blade.php
@extends('layouts.acme.admin.app')

@section('title')
@lang('pages.pages')
@endsection

@push('styles')

@endpush

@section('content')
<div class="app-content content">
    @include ('layouts.acme.admin._card_header', ['routeGroup' => 'admin', 'viewName' => 'pages', 'type' => 'create'])

    <div class="content-body">
        <!-- Form Section -->
        <section class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">@lang('general.create')</h4>
                        <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                        <div class="heading-elements">
                            <ul class="list-inline mb-0">
                                <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="card-content show">
                        <div class="card-body">
                            <form method="POST" class="form form-horizontal" action="{{route('admin.pages.store')}}"
                                enctype="multipart/form-data">
                                @csrf

                                @include ('admin.pages.form', ['formMode' => 'create'])

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--/ Form Sections -->
    </div>
</div>
@endsection

@push('scripts')
<script src="{{asset('ckeditor4/ckeditor.js')}}"></script>
<script src="{{asset('ckeditor4/adapters/jquery.js')}}"></script>

<script>
    $(function () {
            $('#content').ckeditor();
        });
</script>
@endpush

resources/views/admin/pages/edit.blade.php
@extends('layouts.acme.admin.app')

@section('title')
@lang('pages.pages')
@endsection

@push('styles')

@endpush

@section('content')
<div class="app-content content">
    @include ('layouts.acme.admin._card_header', ['routeGroup' => 'admin', 'viewName' => 'pages', 'type' => 'edit'])

    <div class="content-body">
        <!-- Form Section -->
        <section class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">@lang('general.update')</h4>
                        <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                        <div class="heading-elements">
                            <ul class="list-inline mb-0">
                                <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="card-content show">
                        <div class="card-body">
                            <form method="POST" class="form form-horizontal"
                                action="{{route('admin.pages.update', $page->id)}}" enctype="multipart/form-data">
                                @method('PUT')
                                @csrf

                                @include ('admin.pages.form', ['formMode' => 'edit'])

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--/ Form Sections -->
    </div>
</div>
@endsection

@push('scripts')
<script src="{{asset('ckeditor4/ckeditor.js')}}"></script>
<script src="{{asset('ckeditor4/adapters/jquery.js')}}"></script>

<script>
    $(function () {
            $('#content').ckeditor();
        });
</script>
@endpush

resources/views/admin/pages/form.blade.php
<div class="form-body">
    @foreach($languages as $language)
        <div class="form-group{{ $errors->has('name') ? 'has-error' : ''}}">
            {!! Form::label('title'.'_'.$language->code, trans('pages.title') .' '. __('general.'.$language->code), ['class' => 'control-label']) !!}
            {!! Form::text("title"."_"."$language->code", $page->getTranslation('title', $language->code), ('required' == 'required') ? ['class' => 'form-control', 'required' => 'required'] : ['class' => 'form-control']) !!}

            {!! $errors->first('title'.'_'.$language->code, '<p class="text-danger help-block">:message</p>') !!}
        </div>
    @endforeach
    <div class="form-group{{ $errors->has('content') ? 'has-error' : ''}}">
        {!! Form::label('content', trans('pages.content') .' '. __('general.'.$language->code), ['class' => 'control-label']) !!}
        {!! Form::textarea('content', $page->content, ['class' => 'form-control tinymce']) !!}
        {!! $errors->first('content', '<p class="text-danger help-block">:message</p>') !!}
    </div>
</div>
<div class="form-actions text-right">
    <button type="submit" class="btn btn-success">
        <i class="la la-check-square-o"></i> @lang('general.save')
    </button>
</div>

resources/views/admin/pages/index.blade.php
@extends('layouts.acme.admin.app')

@section('title')
@lang('pages.pages')
@endsection

@push('styles')
<style>
    .select2-container {
        width: 100% !important;
    }

    .select2-container--classic .select2-selection--single,
    .select2-container--default .select2-selection--single {
        height: 52px !important;
        padding: 5px;
        width: auto;
        border-color: #717171 !important;
    }
</style>
@endpush

@section('content')
<div class="app-content content">
    @include ('layouts.acme.admin._card_header', ['routeGroup' => 'admin', 'viewName' => 'pages', 'type' => 'index'])
    <div class="content-body">
        <!-- datatable -->
        <section class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">@lang('general.all') @lang('pages.pages')</h4>
                        <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                        <div class="heading-elements">
                            <ul class="list-inline mb-0">
                                <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="card-content collapse show">
                        <div class="card-body card-dashboard">
                            <div class="table  ">
                                <table class="table table-striped table-bordered zero-configuration data-table w-100">
                                    <thead>
                                        <tr>
                                            <th dt-type="text" dt-name="title">{{ trans('pages.title') }}</th>
                                            <th dt-type="text" dt-name="slug">{{ trans('pages.slug') }}</th>
                                            <th style="width: 25%;">@lang('general.action')</th>
                                        </tr>
                                        <tr id="searchable-row" @if(app()->getLocale() == 'ar') dir="rtl" @endif></tr>
                                    </thead>
                                    <tbody>

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--/ datatable -->
    </div>
</div>
@endsection

@push('scripts')
<script>
    var lang = '{{app()->getLocale()}}';
        var dataTablesSearchLink = '{{url('admin/pages')}}';
        const dataTablesLanguageLink = '{{(app()->getLocale() == 'ar')? asset('admin-assets/datatable-lang/ar.json') : asset('datatables/lang/en.json')}}';
</script>
<script src="{{asset('datatables/js/datatable.js')}}"></script>
@endpush

resources/views/admin/pages/show.blade.php
@extends('layouts.acme.admin.app')

@section('title')
@lang('pages.pages')
@endsection

@push('styles')
<style>
    .select2-container {
        width: 100% !important;
    }
</style>
@endpush

@section('content')
<div class="app-content content">
    @include ('layouts.acme.admin._card_header', ['routeGroup' => 'admin', 'viewName' => 'pages', 'type' => 'show'])

    <div class="content-body">
        <!-- datatable -->
        <section class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">@lang('general.show')</h4>
                        <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                        <div class="heading-elements">
                            <ul class="list-inline mb-0">
                                <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="card-content collapse show">
                        <div class="card-body card-dashboard">
                            <div class="table-responsive">
                                <table class="table">
                                    <tbody>
                                        <tr>
                                            <th>ID</th>
                                            <td>{{ $page->id }}</td>
                                        </tr>
                                        <tr>
                                            <th> {{ trans('pages.title') }} @lang('general.'.'en') </th>
                                            <td> {{ $page->getTranslation('title','en') }} </td>
                                        </tr>
                                        <tr>
                                            <th> {{ trans('pages.title') }} @lang('general.'.'ar') </th>
                                            <td> {{ $page->getTranslation('title','ar') }} </td>
                                        </tr>
                                        <tr>
                                            <th> {{ trans('pages.slug') }} </th>
                                            <td> {{ $page->slug }} </td>
                                        </tr>
                                        <tr>
                                            <th> {{ trans('pages.content') }} </th>
                                            <td> {!! $page->content !!} </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--/ datatable -->
    </div>
</div>
@endsection

@push('scripts')

@endpush